version: "3"

services:
  comic-book-reader:
    build:
      context: .
      dockerfile: Dockerfile
    image: comic-book-reader
    container_name: comic-book-reader
    restart: unless-stopped
    ports:
      - "8080:8080"
